from __future__ import annotations

from typing import Protocol


class VocoderBackend(Protocol):
    def encode_pcm_to_ambe(self, pcm_frame: bytes) -> bytes: ...
    def decode_ambe_to_pcm(self, ambe_frame: bytes) -> bytes: ...
    def health_check(self) -> bool: ...
    def reset_stream(self) -> None: ...
    def backend_name(self) -> str: ...


class VocoderUnavailable(RuntimeError):
    pass
