from __future__ import annotations

import argparse
import json
import logging
import random
import threading
import time
from pathlib import Path

from echolink_ob.analog.ports import build_port_plan, render_analog_bridge_ini, write_analog_bridge_ini, write_state_file
from echolink_ob.analog.tlv import RawTlvFrame, extract_dmr_ambe_blocks, listen_raw_tlv, write_tlv_capture
from echolink_ob.analog.usrp import pcm_sine_frames, send_usrp_pcm_frames
from echolink_ob.config import AppConfig, load_config
from echolink_ob.dmr.ambe import build_payload33_from_ambe72_triplet, extract_center48_from_payload33
from echolink_ob.logging_setup import setup_logging
from echolink_ob.openbridge.analyzer import is_possible_stream_end, is_voice_payload, read_capture
from echolink_ob.openbridge.client import OpenBridgeClient
from echolink_ob.openbridge.dmrd import DMRDPacket, MAX_3BYTE_ID, validate_3byte_id
from echolink_ob.openbridge.test_sender import make_client, resolve_source_id

log = logging.getLogger(__name__)


DEFAULT_BUILTIN_TEMPLATE = Path("/opt/echolink-ob/data/templates/default-openbridge-template.dmrd")
DEFAULT_CAPTURE_DIR = Path("/opt/echolink-ob/diagnostics/dmr-captures")


def latest_template_capture(default_dir: str | Path = DEFAULT_CAPTURE_DIR) -> Path | None:
    candidates = sorted(Path(default_dir).glob("stream-*.dmrd"), key=lambda p: p.stat().st_mtime, reverse=True)
    return candidates[0] if candidates else None


def resolve_template_path(arg_template: str | None, *, mode: str = "auto") -> tuple[Path, str]:
    """Resolve the DMRD signalling template before audio generation starts.

    Template resolution is deliberately done before sending USRP audio so a
    missing template does not waste a tone transmission. In auto mode, the app
    prefers the newest local DMR capture and falls back to a bundled no-audio
    template derived from a known-good stream structure.
    """

    if arg_template:
        path = Path(arg_template)
        if not path.exists():
            raise FileNotFoundError(f"template not found: {path}")
        return path, "explicit"

    if mode not in {"auto", "capture", "builtin"}:
        raise ValueError("template mode must be auto, capture, or builtin")

    capture = latest_template_capture()
    if mode in {"auto", "capture"} and capture is not None:
        return capture, "latest-capture"

    if mode == "capture":
        raise FileNotFoundError(
            f"no stream-*.dmrd template found in {DEFAULT_CAPTURE_DIR}; run echolink-ob-record-dmr first, pass --template, or use --template-mode auto/builtin"
        )

    if DEFAULT_BUILTIN_TEMPLATE.exists():
        return DEFAULT_BUILTIN_TEMPLATE, "builtin"

    raise FileNotFoundError(
        f"no stream-*.dmrd template found in {DEFAULT_CAPTURE_DIR} and no built-in template found at {DEFAULT_BUILTIN_TEMPLATE}"
    )


def _cycle(items: list[DMRDPacket], index: int) -> DMRDPacket:
    if not items:
        raise ValueError("template has no voice packets")
    return items[index % len(items)]


def build_openbridge_packets_from_ambe_blocks(
    ambe_blocks: list[bytes],
    template_packets: list[DMRDPacket],
    cfg: AppConfig,
    *,
    source_id: int,
    stream_id: int | None = None,
    sequence_start: int = 0,
) -> list[DMRDPacket]:
    """Wrap Analog_Bridge DMR AMBE blocks in OpenBridge DMRD packets.

    The DMR header/terminator and the 48-bit center sync/embedded signalling
    regions are copied from a known-good captured DMRD stream. The AMBE voice
    regions are replaced with the new audio generated by Analog_Bridge.
    """

    validate_3byte_id(source_id, "source-id")
    if not ambe_blocks:
        raise ValueError("no 27-byte DMR AMBE blocks were captured from Analog_Bridge")
    if any(len(block) != 27 for block in ambe_blocks):
        raise ValueError("all AMBE blocks must be exactly 27 bytes")

    voice_templates = [pkt for pkt in template_packets if is_voice_payload(pkt)]
    if not voice_templates:
        raise ValueError("template capture contains no voice packets")
    first_voice = template_packets.index(voice_templates[0])
    last_voice = max(i for i, pkt in enumerate(template_packets) if is_voice_payload(pkt))
    prefix_templates = [pkt for pkt in template_packets[:first_voice] if not is_voice_payload(pkt)]
    suffix_templates = [pkt for pkt in template_packets[last_voice + 1 :] if is_possible_stream_end(pkt)]
    if not suffix_templates:
        # Prefer a real terminator when present, but do not make tone tests impossible.
        suffix_templates = [pkt for pkt in template_packets[last_voice + 1 :] if not is_voice_payload(pkt)][:1]

    out_stream_id = int(stream_id if stream_id is not None else random.randint(1, 0xFFFFFFFF))
    seq = sequence_start % 256
    output: list[DMRDPacket] = []

    def rewrite(pkt: DMRDPacket, payload: bytes | None = None) -> DMRDPacket:
        nonlocal seq
        new_pkt = DMRDPacket(
            sequence=seq,
            rf_source_id=source_id,
            destination_id=cfg.openbridge.fixed_tgid,
            network_id=cfg.openbridge.network_id,
            slot=cfg.openbridge.slot,
            call_type="group",
            frame_type=pkt.frame_type,
            dtype_vseq=pkt.dtype_vseq,
            stream_id=out_stream_id,
            payload=pkt.payload if payload is None else payload,
        )
        seq = (seq + 1) & 0xFF
        return new_pkt

    for pkt in prefix_templates:
        output.append(rewrite(pkt))

    for index, block in enumerate(ambe_blocks):
        template = _cycle(voice_templates, index)
        center = extract_center48_from_payload33(template.payload)
        payload = build_payload33_from_ambe72_triplet(
            [block[0:9], block[9:18], block[18:27]],
            center48=center,
        )
        output.append(rewrite(template, payload=payload))

    for pkt in suffix_templates[:1]:
        output.append(rewrite(pkt))

    return output


def send_packets(client: OpenBridgeClient, packets: list[DMRDPacket], *, packet_ms: float) -> None:
    delay = max(0.0, packet_ms / 1000.0)
    for pkt in packets:
        client.send_packet(pkt)
        if delay:
            time.sleep(delay)


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description=(
            "Generate an audible PCM tone, encode it through Analog_Bridge, wrap the returned DMR TLV audio "
            "in OpenBridge DMRD packets using a known-good DMRD template, and send it to HBlink3."
        )
    )
    p.add_argument("--config", default="/opt/echolink-ob/config/config.toml")
    p.add_argument("--seconds", type=float, default=3.0)
    p.add_argument("--frequency", type=float, default=1000.0)
    p.add_argument("--amplitude", type=int, default=6000)
    p.add_argument("--capture-seconds", type=float, default=6.0)
    p.add_argument("--output-dir", default="/opt/echolink-ob/diagnostics/analog-tone-openbridge")
    p.add_argument("--template", default=None, help="known-good stream-*.dmrd template; overrides auto template selection")
    p.add_argument("--template-mode", choices=["auto", "capture", "builtin"], default="auto", help="auto uses newest capture if present, else built-in no-audio template")
    p.add_argument("--source-id", type=int, default=None, help=f"DMR RF source ID, 0..{MAX_3BYTE_ID}; defaults to fallback_source_id")
    p.add_argument("--stream-id", type=int, default=None, help="force outgoing OpenBridge stream ID")
    p.add_argument("--packet-ms", type=float, default=60.0)
    p.add_argument("--dry-run", action="store_true", help="generate/capture/build packets but do not send OpenBridge")
    p.add_argument("--no-write-analog-config", action="store_true")
    return p


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    cfg = load_config(args.config)
    setup_logging(cfg.logging.level, cfg.logging.log_file)
    source_id = resolve_source_id(cfg, args.source_id, parser)
    try:
        template_path, template_source = resolve_template_path(args.template, mode=args.template_mode)
        template_packets = read_capture(template_path, cfg.openbridge.passphrase)
    except Exception as exc:
        parser.error(str(exc))

    result = build_port_plan(cfg, allow_in_use=True, reuse_state=True)
    if not args.no_write_analog_config:
        write_state_file(cfg.port_manager.state_file, result)
        write_analog_bridge_ini(result.plan.analog_bridge_ini_path, render_analog_bridge_ini(cfg, result.plan))

    plan = result.plan
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    captured: list[RawTlvFrame] = []

    def capture_tlv() -> None:
        try:
            for frame in listen_raw_tlv(plan.host, plan.app_tlv_rx_port, seconds=args.capture_seconds):
                captured.append(frame)
                log.info("analog_tlv_received bytes=%s source=%s:%s", len(frame.data), frame.source[0], frame.source[1])
        except OSError as exc:
            log.error("analog_tlv_capture_failed port=%s error=%s", plan.app_tlv_rx_port, exc)

    thread = threading.Thread(target=capture_tlv, daemon=True)
    thread.start()
    frames = pcm_sine_frames(seconds=args.seconds, frequency_hz=args.frequency, amplitude=args.amplitude)
    sent = send_usrp_pcm_frames(target_host=plan.host, target_port=plan.app_usrp_tx_port, frames=frames, talkgroup=cfg.openbridge.fixed_tgid)
    log.info("analog_usrp_tone_sent frames=%s host=%s port=%s seconds=%s frequency=%s", sent, plan.host, plan.app_usrp_tx_port, args.seconds, args.frequency)
    thread.join(timeout=args.capture_seconds + 1.0)

    raw_tlv_path = output_dir / "analog-tone-openbridge.tlvraw"
    if captured:
        write_tlv_capture(raw_tlv_path, captured)
    blocks = extract_dmr_ambe_blocks(captured)
    if not blocks:
        parser.error("no 27-byte DMR AMBE audio blocks captured from Analog_Bridge; check that Analog_Bridge is running with the generated ini")

    try:
        packets = build_openbridge_packets_from_ambe_blocks(
            blocks,
            template_packets,
            cfg,
            source_id=source_id,
            stream_id=args.stream_id,
        )
    except Exception as exc:
        parser.error(str(exc))

    dmrd_out = output_dir / "analog-tone-openbridge.dmrd"
    dmrd_out.write_bytes(b"".join(pkt.to_raw53() for pkt in packets))

    report = {
        "usrp_tone_frames_sent": sent,
        "tlv_frames_captured": len(captured),
        "ambe_blocks_27_bytes": len(blocks),
        "openbridge_packets_built": len(packets),
        "source_id": source_id,
        "tgid": cfg.openbridge.fixed_tgid,
        "network_id": cfg.openbridge.network_id,
        "slot": cfg.openbridge.slot,
        "template": str(template_path),
        "template_source": template_source,
        "analog_bridge_ini": result.plan.analog_bridge_ini_path,
        "tlv_raw": str(raw_tlv_path) if captured else None,
        "dmrd_output": str(dmrd_out),
        "dry_run": bool(args.dry_run),
        "note": "Experimental Analog_Bridge TLV to OpenBridge tone test. It copies or falls back to DMR signalling fields from a template; voice audio is generated live through Analog_Bridge.",
    }
    report_path = output_dir / "analog-tone-openbridge-report.json"
    report_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    log.info(
        "analog_tone_openbridge_plan usrp_frames=%s tlv_frames=%s ambe_blocks=%s ob_packets=%s template=%s dry_run=%s",
        sent,
        len(captured),
        len(blocks),
        len(packets),
        template_path,
        args.dry_run,
    )

    if not args.dry_run:
        client = make_client(cfg)
        try:
            send_packets(client, packets, packet_ms=args.packet_ms)
            log.info("analog_tone_openbridge_sent packets=%s", len(packets))
        except KeyboardInterrupt:
            log.info("analog_tone_openbridge_interrupted")
            return 130
        finally:
            client.close()

    print(json.dumps(report, indent=2, sort_keys=True))
    print(f"report={report_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
